<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewEmployee.aspx.cs" Inherits="EmployeeProject._Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 23px;
        }
        .auto-style2 {
            height: 39px;
        }
    </style>
    <script type="text/javascript">
        function UpdateFunction() {
            var result = confirm("Do you want to delimit the record?")
            if (result) {
                return true;
            }
            else {
                return false;
            }


        }

    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <table style="width:100%;" frame="border">
            <tr>
                <td align="center" style="margin-left: 80px" valign="middle" class="auto-style2">
                    <asp:Label ID="lblViewEmployee" runat="server" Font-Size="XX-Large" Text="View Employee"></asp:Label>
                </td>
                <td align="left" class="auto-style2">
                    <asp:Button ID="btnCreateEmployee" runat="server" Text="Create" ToolTip="Click to Create a New Employee" OnClick="btnCreateEmployee_Click" />
                </td>
            </tr>
            <tr>
                <td align="center" class="auto-style1" colspan="2" valign="middle">
                    <asp:GridView ID="gvViewEmployee" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" EnableModelValidation="True" ForeColor="#333333" GridLines="None" OnRowDeleted="gvViewEmployee_RowDeleted" OnRowDeleting="gvViewEmployee_RowDeleting" DataKeyNames="EmployeeID" OnRowEditing="gvViewEmployee_RowEditing" >
                        <AlternatingRowStyle BackColor="White" />
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td align="center" class="auto-style1" colspan="2" valign="middle">
                    <asp:Label ID="lblStatus" runat="server" Text="Status" Visible="False"></asp:Label>
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
